### ISSUE TITLE
np.test() or our tests need array len > 100K to test multithreaded

### ISSUE THREAD

**Issue by tdimitri** [Quansight/numpy-threading-extensions#27]
larger array tests need for MT to kick in

**Comment by tdimitri** [comment]
Example of possible issues:

Test below checks for bool handling values above 1, which is a good test, which we failed earlier.
However, the array size is too small to even hit the vector code (requires at least 32 bools in AVX-256 mode).

```
data = np.arange(10, dtype=np.uint8).reshape(-1, 2).view(bool)
result = np.array([[False, True], [True, True]], dtype=bool)
unique(data, axis=0)

```

**Comment by mattip** [comment]
Fixed in the few tests we have
