### ISSUE TITLE
Test vs Run dependencies

### ISSUE THREAD

**Issue by kcpevey** [Quansight/numpy-threading-extensions#38]
In the tox init, there are dependencies for individual tests. There is also a `requirements.txt` file. Is the idea to keep the run dependencies separate from the test dependencies? If so, why is the `requirements.txt` file in the ci folder?

**Comment by mattip** [comment]
The ci/requirements.txt is needed to install dependencies in order to run CI. Then once tox is properly installed, the tox run installs actual project dependencies. So both are required.
