### ISSUE TITLE
Example templated vector intrinsic loop

### ISSUE THREAD

**Issue by tdimitri** [Quansight/numpy-threading-extensions#4]
I suggest we use up to C++ 11 std since that is the highest version required and works in the 3 compilers I have tested.

Please note that the Microsoft compiler assumes Unaligned Loads and the gcc, clang assume Aligned Loads.  Thus there is a a LOADA, LOADU, STOREA, STOREU macros per compiler.

This may seem like a small difference in compilers, but it causes trouble when optimizing some loops, especially because many Intel/AMD vector instructions do not care if the memory is aligned.  Those that do require alignment have to either use LOADA (an extra instruction) or process a few members of the input array until it is on the aligned memory boundary.

I write C code in CamelCase since I used to work on the NT Kernel in the 90s but I dont care if others prefer lower case underscore linux style.

I believe a possible universal unary C api signature looks like:
`void UnaryOpFast(void* pDataIn, void* pDataOut, const INT64 len, const INT64 strideIn, const INT64 strideOut) ;
`
_**where**_ 
pDataIn is the pointer to the input array
pDataOut is the output array
len is the length of both input/output arrays
and then the strides.

In this loop design, it assumes that what is left over (from the first vector loop) can be handled in a normal loop.  This loop design also handles multiple vector bit widths: 128/256/512.
```
#define STRIDE_NEXT(_TYPE_, _MEM_, _STRIDE_) (_TYPE_*)((char*)_MEM_ + _STRIDE_)

//-------------------------------------------------------------------
// T = data type as input (such as INT8, INT64 or float)
// MATH_OP Math operation to perform (non vector)
// VECTOR_TYPE such as mm128i, mm256i, mm512i
// VECTOR_OP Vector operation to perform such as _mm256_abs_epi8
//
template<typename T, typename VECTOR_TYPE, const T MATH_OP(T), const VECTOR_TYPE VECTOR_OP(VECTOR_TYPE)>
static inline void UnaryOpFast(void* pDataIn, void* pDataOut, const INT64 len, const INT64 strideIn, const INT64 strideOut) {

    T* pIn = (T*)pDataIn;
    T* pOut = (T*)pDataOut;
    T* pLastOut = (T*)((char*)pOut + (strideOut * len));

    // chunkSize is how many calculations each vector instruction can calculate
    INT64 chunkSize = sizeof(VECTOR_TYPE) / sizeof(T);

    // If stride size matches, the array is contiguous
    if (sizeof(T) == strideOut && sizeof(T) == strideIn && len >= chunkSize) {

        T* pEnd = &pOut[chunkSize * (len / chunkSize)];
        VECTOR_TYPE* pEndVector = (VECTOR_TYPE*)pEnd;

        VECTOR_TYPE* pInVector = (VECTOR_TYPE*)pIn;
        VECTOR_TYPE* pOutVector = (VECTOR_TYPE*)pOut;

        do {
            // Use vector registers (i.e. 256 bit registers which hold 8 floats or 4 doubles)
            // The first operand should allow unaligned loads
            STOREU(pOutVector, VECTOR_OP(*pInVector));
            ++pInVector;
            ++pOutVector;

        } while (pOutVector < pEndVector);

        // update thin pointers to last location of wide vector pointers
        pIn = (T*)pInVector;
        pOut = (T*)pOutVector;
    }

    // Slow loop, thin pointers, handle 1 at a time
    while (pOut != pLastOut) {
        *pOut = MATH_OP(*pIn);
        pOut = STRIDE_NEXT(T, pOut, strideOut);
        pIn = STRIDE_NEXT(T, pIn, strideIn);
    }
}

```
Then I would presume we build tables with 
[UFUNC enum][DTYPE]

For instance if the UFUNC is np.abs that might have an enum of 13.  If the DTYPE is INT8, that might have an enum of 2.  So we might request the function to call which always has this C API signature -> 
`void UnaryOpFast(void* pDataIn, void* pDataOut, const INT64 len, const INT64 strideIn, const INT64 strideOut)
`
Then to insert the optimized loop for np.abs with int8 the code might look like:

```
template<typename T> static const inline T ABS_OP(T x) { return x < 0 ? -x: x; }

static const inline __m256i ABS_OP_256i8(__m256i x) { return _mm256_abs_epi8(x); }
static const inline __m512i ABS_OP_512i8(__m512i x) { return _mm512_abs_epi8(x); }

      case NPY_INT8:   return UnaryOpFast<INT8, __m256i,  ABS_OP<INT8>, ABS_OP_256i8>;
for AVX-512
      case NPY_INT8:   return UnaryOpFast<INT8, __m512i,  ABS_OP<INT8>, ABS_OP_512i8>;
```
Many Unary Ops + Dtypes for 128, 256, 512 are built with the same loop.
So if we have 30 unary ops and 12 dtypes and 3 vector sizes...  => 1080 table entries

I have avoided the topic of using instructions like _mm256_i32gather_ps  which can pull from strided arrays.  I leave that as a future improvement.

I have also avoided the topic of multi-dimensional arrays, as those are often outer loops that call into the above inner loop.

**Comment by tdimitri** [comment]
In this example, for the numpy portion of code I assume:
* If user passed in a list, we converted it to an array
* Any nec. upcasting/downcasting has already taken place
* if the output array needs to be allocated, we have done that, or used the output array the user provided
* array lengths or broadcast rules have been checked already
* any array overlap rules have been checked
* the enum for the array operation is known (for instance operation np.abs might be enum 13)
* the numpy extension has loaded and detected the chip's capabilities (for instance AVX-256 support)

Then new code will be inserted into lower level numpy that may look something like this (assumes 1 dim array):
```
typedef void(*UNARY_OP)(void* pDataIn, void* pDataOut, const INT64 len, const INT64 strideIn, const INT64 strideOut);
#define FUNCTION_ABS_OPCODE 13

// See if the numpy extension can handle the operation for this dtype
// If it cannot, NULL will be returned
UNARY_OP pFastUnaryFunction =  numpy_extension.get_unary_function(FUNCTION_ABS_OPCODE , PyArray_TYPE(inputArray))
if (pFastFunction) {
    pFastUnaryFunction(PyArray_BYTES(input), PyArray_BYTES(output), ArrayLength(input), PyArray_STRIDE(input,0), PyArray_STRIDE(output,0));

} else {
    // call normal numpy routine that was there
}
```

**Comment by mattip** [comment]
There is support for much of this already in NumPy, maybe we can reuse as much as possible.

NumPy allows setting the inner loop function via [`PyUFunc_ReplaceLoopBySignature`](https://numpy.org/devdocs/reference/c-api/ufunc.html?highlight=pyufunc_registerloopfortype#c.PyUFunc_ReplaceLoopBySignature), so it would be easiest if our solution followed that design pattern. This solves the problem of matching a function to the dtypes since it registers a specific function for the dtypes used in its `argin` and `argout`, and is an alternative to the `gUnaryFuncLUT`. 

NumPy currently has a subsystem for detecting available CPU features at runtime, based on the work done to support [unversal intrinsics](https://numpy.org/neps/nep-0038-SIMD-optimizations.html). This is ongoing work for the next version of NumPy, the compile side support is partially documented [here](https://numpy.org/devdocs/reference/simd/simd-optimizations.html?highlight=simd#simd-optimizations). The runtime supported features are exposed to python via `numpy.core._multiarray_umath.__cpu_features__`, and are also available to the C level, so we can reuse this in the extension to decide which loops to override via `PyUFunc_ReplaceLoopBySignature`.

The ufunc mechanism takes care of preparing and validating the arguments to the loop, so we will need to provide functionality in C to get from the loop signature
```
template<typename T, typename VECTOR_TYPE, const T MATH_OP(T), \
    const VECTOR_TYPE VECTOR_OP(VECTOR_TYPE)>
static inline void UnaryOpFast(void* pDataIn, void* pDataOut, const INT64 len, \
                                                const INT64 strideIn, const INT64 strideOut)
```

to match `PyUFuncGenericFunction` + signature (c-array of dtype enums) used in `PyUFunc_ReplaceLoopBySignature` which is 
```
void loopfunc(
char** args, npy_intp const *dimensions, npy_intp const *steps, void* data)
```

where `args = {pDataIn, pDataOut}`, `dimensions=&len`, `steps={strideIn, strideOut}, and `data=NULL`, we would map `T` to the dtype enums, and `MATH_OP(T)` to the ufunc.

You can see some sample code to set this all up in the [numpy tests](https://github.com/numpy/numpy/blob/master/numpy/core/src/umath/_rational_tests.c.src#L1204) where they define a new dtype, "rational", and register ufuncs for it via the same-but-for-user-defined-dtypes `PyUFunc_RegisterLoopForType`.

**Comment by tdimitri** [comment]
Thank you Matti.  Is a goal to map the templated C interfaces to what numpy wants?  Or is a goal to write the templated C routines independently (allowing use by other languages)?  I think we need to answer that question as it will likely change the design.
I would assume the templated C package has no knowledge of numpy internals or dtypes - for instance in numpy, the dtype for int32 and int64 is often repeated because numpy used int, long, and long long (instead of int32/64).
What happens with 2d arrays -- do they call another routine or do they call the 1d routine?
For upcasting an array -- in riptable we have to convert -MAXINT to nan so we want to take over array conversions.
Then as we keep taking over functionality, what happens when a boolean or fancy index mask is applied to an array -- can that be taken over?
And so on... for instance knowing the boolean sum is an important function that is sometimes used to calculate boolean mask output length.  Therefore the routine to calculate the boolean sum would live in the new templated C  package.

It sounds to me like there is templated C package which will end up having many independent array math routines (perhaps with permission, pulling in some of the best routines from other places).  Then a new python package will glue numpy to the C package by calling numpy with a series of hooks.  One of those hooks is likely PyUFunc_ReplaceLoopBySignature.
The new python package will also handle configuration of threads and array allocation.

**Comment by tdimitri** [comment]
Today, it is difficult for an outside developer to work on internal numpy algorithms because:
1) any changes may break millions of users (revisions are closely reviewed, with a NEP process)
2) cannot add templated code (templates are mimicked via loading different .h files and macro expansion)
3) the core numerical algorithms are coupled to python and numpy dtypes
4) little knowledge or use of threading
5) has to compile for 32bit and work across a wider array of existing platforms

i advocate decoupling numpy algorithms from 
1) plain  C
2) numpy dtypes, pyarray, and includes
3) python routines, linkage, and includes
4) legacy burden of numpy edge cases and parsing, 32 bit support
5) numpy idiosyncrasies (such as int/long/long long usage and duplicate dtypes).

while also providing the new algorithms the ability to use:
1) templates
2) threading
3) vector intrinsics
4) array memory management or recycling (optional)
5) language and platform independent interfaces

in a decoupled world, more outside developers can contribute and improve algorithms (and those algorithms can work on more languages than just python).

threading alone works its way into > 80% of all numpy loops -- from unary, binary, filtering, sorting, stacking, putmask, where, linear interpolations, unique, tile, repeat, std, arange and so forth.  To me, all those routines belong in a separate, decoupled, template capable, thread aware math package that more developers can contribute to.

**Comment by mattip** [comment]
> Is a goal to map the templated C interfaces to what numpy wants? Or is a goal to write the templated C routines independently (allowing use by other languages)? I think we need to answer that question as it will likely change the design.

I thought the goal in this issue is to allow you to write ufunc loops with a C++ templated signature similar to the one you proposed above, and use these in NumPy ufuncs, which can be done via the NumPy C-API.

If the goal is to override __any__ NumPy function, not just ufuncs, then the focus changes, and I would suggest writing a full `ndarray` replacement using `__arrray_function__` ([NEP 35](https://numpy.org/neps/nep-0035-array-creation-dispatch-with-array-function.html)), `_array_ufunc__` ([NEP 13](https://numpy.org/neps/nep-0013-ufunc-overrides.html)) and `_array_module__` ([NEP 37](https://numpy.org/neps/nep-0037-array-module.html)), in the spirit of [cupy](https://docs.cupy.dev/en/stable/).

In either case, I think this project would provide the "glue" enabling the new agreed-upon function declarations to be called from python, with example implementations proving the concept is valid.

**Comment by tdimitri** [comment]
To me, the overarching goal is to mulithread numpy algos in a safe opt-in manner.  I started with the simplest example I could think of, how to multithread a unary func like np.abs so that we could discuss if there was interest (because before we were directed to the PyData consortium, which was not the place for this discussion).  Now, I hope we have a forum to discuss the design - the creation of a templated threaded C code lib and the concept of a new python module "numpy-extensions" that glues together numpy with the C lib.

If I write a routine to multithread np.abs or np.add, who is going to use it and maintain it?  Maybe 1% of the numpy user base will use it, and maybe I can convince a few developers to help maintain it.  So to me, that does not make much economic sense.

However if there is a default module (call it numpy-extensions) that is promoted and becomes the de facto module to write multithreaded numpy-like algorithms, then > 20% of numpy users will likely use it, and many more will be interested in maintaining it.  I can also request (and likely to receive) more funding towards this project.  Further it can serve as a fully functional example for other developers wishing to extend numpy.

For example..
```
x = np.arange(1_000_000)
y = np.arange(1_000_000.0)
%timeit np.add(x , y)
```
Now once the user imports numpy-extensions... suddenly it is x3 faster 
```
import numpy-extensions as ne
ne.Threading.on()
%timeit np.add(x, y)
```
x1=x and y1=y in the example below (real timings I just ran on my PC for same arrays)
[example1](https://github.com/tdimitri/pydata/blob/master/npadd.png)

**Comment by tdimitri** [comment]
@mattip asked me for which routines we multithreaded.

I wrote this brief document: 
[threading in riptable](https://github.com/rtosholdings/riptable/blob/master/docs/THREADING.md
)

This can serve as a rough goal of the total scope of multithreading (it seeps into almost every operation).  Since the footprint is large, I would expect it to be done in phases, with multiple payments and contributions.

50% of what we wrote was to speed up numpy -- another 50% was related to pandas like functionality... especially related to operations over groups.  The perform an operation over a group, we need to have a concept of what a group is -- in riptable we use the Categorical class.  Once numpy expands into groupby operations, another world will open up.

**Comment by tdimitri** [comment]
Example of single unary function and ColMajor vs RowMajor loops.
This is linked back to riptide_cpp, which handles most strided cases (up to 2d arrays).
Purpose of this code is to demonstrate that only one call signature of the unary operation is required, no matter what the strides or number of array dimensions.  Further, with a little more work, any strided case with any number of dimensions can be multithreaded (if enough data to make it worth the effort).

```
    if (directionIn == 1 && directionOut == 0) {
            // Row Major 2dim like array with output being fully contiguous
            INT64 innerLen=1;
            for (int i = directionIn; i < ndim; i++)  innerLen *= PyArray_DIM(inArray, i);
            
            // TODO: consider dividing the work over multiple threads if innerLen is large enough
            const INT64 outerLen = PyArray_DIM(inArray, 0);
            const INT64 outerStride = PyArray_STRIDE(inArray, 0);

            for (INT64 j = 0; j < outerLen; j++) {
               pUnaryFunc((char*)pDataIn + (j * outerStride), (char*)pDataOut + (j * innerLen * strideOut), innerLen, strideIn, strideOut);
            }
         }
```
[UnaryOps.cpp code](https://github.com/rtosholdings/riptide_cpp/blob/master/src/UnaryOps.cpp#L1899-L1901
)

**Comment by mattip** [comment]
I have merged an example loop replacement c-extension in the first-loop branch, please take a look. The UFunc mechanism prepares the arguments for the inner loop and expects a signature like [`template <class T> void add_T(T **args, npy_intp const *dimensions, npy_intp const *steps, void *innerloopdata)`](https://github.com/Quansight/numpy-threading-extensions/blob/main/src/fast_numpy_loops/_fast_numpy_loops.cpp#L12) where `args` are pointers to the input and output data, `dimensions` are the shapes, and `steps` are the strides in bytes of each dimension. 

In light of the progress being made with NumPy and SIMD extensions (including using gather-scatter techniques and optimized tables for trigonometric functions) internally, I think we should concentrate on adapting the multi-threading power of riptable to the ufuncs, based on benchmarks that show it is faster than NumPy.

**Comment by tdimitri** [comment]
In the current numpy loop replacement mechanism, for a multidimensional non-contig array the outside loop is controlled by numpy, and thus the inside loop has to keep checking if the array is large enough to multithread (a simple length check).  There is also no opportunity to multithread the outside loop.  Minor issue.

**Comment by mattip** [comment]
Can we close this?

**Comment by tdimitri** [comment]
yes we can
