### ISSUE TITLE
Improving doc strings

### ISSUE THREAD

**Issue by kcpevey** [Quansight/numpy-threading-extensions#42]
Porting this conversation from slack:  

It seems like the basic setup of autodoc using sphinx will just pick up the one-line doc string that we’re using for the python-c connection, e.g. here https://github.com/Quansight/numpy-threading-extensions/blob/main/src/fast_numpy_loops/module_init.cpp#L40

A bit of googling tells me there is a way to use the c docs with sphinx using doxygen and breathe . Is that worth doing? Or do we want to write api docs “by hand”? How do other c-extension packages handle this?

From @mattip :
>We should write better docstrings for the python functions like newinit. I have an idea how to refactor them out into other files. Breathe and doxygen are better for pure c functions

@mattip What is your idea?

**Comment by mattip** [comment]
We should either 
- do what numpy/pytorch do and expose a `_add_docs()` c-function that is exposed via the module, this is used by a python-level function after the module is imported to mangle the empty tp_doc pointer (which is a hack but others do it) or
- add a python function that takes docstring snippets, converts them into C strings and creates a large header file that is then baked into the module at build time.

I am starting the second option on a branch today.

**Comment by mattip** [comment]
docstrings are now generated via the `_add_newdocs.py` file.
