### ISSUE TITLE
Project Name and Mailing List

### ISSUE THREAD

**Issue by rpekrul** [Quansight/numpy-threading-extensions#58]
- [ ] Assign a project name.  (Current name is Fast Numpy Loops) @jack-pappas @tdimitri any ideas?

- [ ] Identify the community communication channels (Gitter, Mailing List, etc...) @jack-pappas @tdimitri any preferences here?

Sample name suggestions for to start the discussion:
* numpy-threaded-hyperloops
* numpy-accelerated-loops
* numpy-threading-extensions (existing repo name)

**Comment by mattip** [comment]
Closing, we have `pnumpy` and a [Google Groups mailing list](https://groups.google.com/g/pnumpy)
