### ISSUE TITLE
BUG: Incorrect sum result when threading is activated?

### ISSUE THREAD

**Issue by seberg** [Quansight/numpy-threading-extensions#84]
Trying around a bit, it seems like you have a nice speedup (e.g. for exp, etc.) and also for simple functions (although I am not sure if NumPy 1.20 will catch up due to SIMD usage. I thought that reductions might be problematic (due to NumPy's buffer) but it seems they do at least gain a bit.

I just found this potential bug though:
```
In [47]: np.sum(np.arange(100000000))                                                                                   
Out[47]: 3859500925368766336

In [48]: fn.thread_disable()                                                                                            

In [49]: np.sum(np.arange(100000000))                                                                                   
Out[49]: 4999999950000000
```
I get the same difference when using double precision `np.arange(100000000.)`. NumPy 1.19.4 gives the correct result in all cases.

EDIT: Thought I would run it through valgrind to see if there is anything odd, I only get an "address range perm" warning, but it happens also without import/initializing this package.

**Comment by tdimitri** [comment]
Sebastian @seberg which version of numpy has the bug?  1.19.3? 
When doing sum, it will allocate a temp array for as many work items there are (usually divides by CHUNK_SIZE which is 16384.
Then it will sum all the smaller chunks, then it will add (or whatever the reduce function) the temporary array it allocated earlier.

**Comment by seberg** [comment]
Sorry, yes, this is was with a pip installed 1.19.4 (which is de-facto identical to 1.19.3).

I just bisected where it goes bad, and the first size `np.arange(size)` where it fails is `8421376`.

**Comment by tdimitri** [comment]
Ok I am checking in a solution soon.  To me, the root issue is how numpy handles reduce functions.  Instead of breaking out reduce functions for things like sum, prod, min, argmax, it has chosen to

1) Uses the same call signature as the binary function even though there is only one array to loop over
2) Uses a "start value", for instance sum has a start value of 0, and prod has 1.0  (this is the bug you encountered).
3) Uses setbufsize logic, I presume to increase accuracy, but this make multiple passes and allocates an unnec. buffer.
4) Does not allow for inplace upcasting in reduce functions to increase accuracy (for instance when adding float32, it can be internally upcast to float64... add all the numbers in float64, and return the final result in float32).
5) Does not currently allow a ufunc hook for some reduce functions like np.std, np.argmax
6) I believe is unaware how to short circuit for certain functions like np.all()/any()
7) Every binary function has to call IS_BINARY_REDUCE() because the ufunc call is overloaded

None of these problems would exist if numpy broke out the reduce functions from the ufunc binary routines and removed the setbufsize logic.

The bug is that we set np.setbufsize to 8192*1024, so when the array length exceeds that value, numpy will call sum multiple times.  The start value from the first pass result is then used by all threads (instead of 0), and thus the summation is wrong.

So now we have to write another routine that understands what the first start value is different dtypes and different functions, for instance sum uses 0 as the startval and prod uses 1.0.  min on the other hand should probably use the start value passed, even when threading.

**Comment by seberg** [comment]
Yes, I realize that this project hits very clear limits in NumPy, and part of my hope is that redoing ufuncs will also help such a project as here (but it is not my priority right now). Matti will know about this, I tried to write down the relevant things here: https://numpy.org/neps/nep-0043-extensible-ufuncs.html in the `ArrayMethod` part.

To go through some of your points:

1. Yes, I don't currently plan on changing this, but it is plausible we should allow explicitly specialized loops. One note: Reductions currently do *not* always use reduction loops! `np.ones((2000, 2000)).sum(axis=1)` will not do an inplace addition, as that is the faster memory order. (Not that NumPy is super good at this, it does not have a blocked iterator unfortunately).
2. I am surprised that the start-value is problematic, it seems fairly elegant. But I suppose it part of the puzzle for you.
3. The buffer size is just a random value that is hopefully large enough to amortize overheads and small enough to ensure all buffers fit comfortably in the cpu cache, there are no accuracy concerns. (Maybe there should be, I admit.)
4. Right, for this you would need working memory. We will need this internally (but have to decide to make it public). Feedback on NEP 43 above, might make that easier, since it will be an easier step to transition from private->public API than invent new API probably.  The fact is we do use working memory for casts internally and I want to make casts and ufuncs share the same core machinery. We will definitely have it, I just have not made up my mind on how to make it public as I do not need it and have hardly any input on it.
5. We would probably call std, argmax, etc. "reduce-like" functions rather than reductions, because there is no ufunc so that `ufunc.reduce` can clearly work.  They can be written as generalized ufuncs, but unfortunately are not and we have the problem that ufuncs currently do not support kwargs (this means we would need multiple ufuncs, or implement that first).  Making std, argmax, etc. generalized ufuncs is a contribution we would accept I think (std is currently implemented in Python though).  So this is something we would love, but it might be very involved to actually get there.
6. Yes, short circuiting is only half existing: You can short circuit each individual call, but there are two problems:
    * You cannot stop the out iteration at all (in a sense I don't think this is super important)
    * But: This means that `np.any()` and `np.all()` may cast every element to `bool` even when the result is already clear.
    I think we should probably add short circuiting, but I didn't want to actually specify it yet (I already get very little feedback, adding more things is not going to make that easier). I.e. ufuncs need a return value `-1` for error, `0` for success and positive values could mean "break outer loop".
7. My redesign would allow that to be moved to an earlier step. (But, I am mainly concerned with NumPy internals right now, I do not need this to be public API to do what I need to do.)

I expect, what you will really want in the end is full control over the iteration which would require more public API.

It is the slow road, but if we can pick up the pace a bit in NumPy (and some feedback can help), we should be able to talk about creating such an experimental API maybe in the 1.21 release.  It isn't my explicit goal right now, but my refactors are the necessary step, and they are very much under way.

**Comment by tdimitri** [comment]
Thank you for understanding.  Yes, can I sign up for no "setbufsize" ?
To me, there are known common reduction routines: sum, min, nansum, nanargmax, std, var, any, all, and others.   Those all fall in the reduction category.  I am sure users will come up with more reduction functions like bitcount, crc, or other hash results.

Just like we can hook a binary function like "add", "subtract", it would be nice to hook a reduction function like "sum" or "std".
To me, sum() is a routine that stands on its own... I do not think it needs to be inside the same function for np.add.  A 1d sum() doesn't need to be broken down into smaller chunks, it can break it down itself.  If the array is partitioned across threads or multiple computers, I prefer to hand over the entire computation to the function and let it do its job.  If that involves internal upcasting, or multiple threads, or multiple computers or GPUs, so be it.

So yes, you are correct, I would prefer to be hooked in a tad higher up the compute chain.

Currently, I believe there is no way to stop setbufsize from chaining the sum results for large 1d arrays, but it would be nice if that was an option in the future (or just a higher level hook is really all that is needed).

Until then I will check in a fix soon.  Thank you.

**Comment by seberg** [comment]
Disabling the buffer when no casting is necessary is a performance issue unrelated to any big changes (Matti has opened this issue on NumPy: https://github.com/numpy/numpy/issues/17471).  It should be possible to address it unrelated to any other changes, but you will not be able to *rely* on no buffering, just most of the time buffering will be disabled, which would be much better also for NumPy itself.

The unfortunate thing, that part of NumPy is rather tricky, so I did not prioritize it yet (there is a small patch that works, but it needs some love and I am not quite sure it is the right spot to address it).

Thanks for the fix!

**Comment by tdimitri** [comment]
I checked in a fix.  For sum with float32 the atop loop will internally upcast (added a new template routine).
There is some new code to understand the starting val in _pnumpy.cpp (which was part of the bug before).
Not sure what innerloop is used for, but I pass it to the original numpy routine when atop_disable() is called.
I notice that for np.tan, innerloop must be passed.

```
In [1]: import numpy as np
In [2]: import pnumpy as pn
In [3]: pn.initialize()
In [4]: x=np.arange(10_000_000, dtype=np.float32)
In [5]: x.sum()
Out[5]: 49999996000000.0
In [6]: %timeit x.sum()
1.04 ms ± 5.96 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
In [7]: pn.atop_disable()
In [8]: pn.thread_disable()
In [9]: %timeit x.sum()
6.78 ms ± 85.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
In [10]: x.sum()
Out[10]: 49999996000000.0

```

**Comment by seberg** [comment]
I should browser your code a bit some time. `innerloop` is often called `innerloop_data` also. You can actually customize what is passed in...

With some small/theoretical exceptions it is a static `void *`.  NumPy uses is mostly to implement math functions and wrapping of Python functions (I have no idea what that means overhead wise)/. In this case the `tan` function for a single element is probably passed in as the `innerloop_data`. As you noticed, most math functions do not use it.
